### ISSUE TITLE
IE11 语法错误

### ISSUE THREAD

**Issue by zhangjw-ECHO** [yiwuyu/vue-ueditor#1]
SCRIPT16389: 未指明的错误。
localhost:8089 (1,1)
HTML1300: 进行了导航。
localhost:8089
polyfill-eventsource added missing EventSource to window
You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html
SCRIPT1002: 语法错误
app.js (852,1)

**Comment by yiwuyu** [comment]
我这里只看到了SCRIPT1002的语法错误
分析代码原因初步认定是引入的clickoutside未进行ES5编译导致的IE无法识别ES6代码
这个BUG正在修复中

SCRIPT16389: 未指明的错误
可详细描述一下此BUG

**Comment by zhangjw-ECHO** [comment]
谢谢
我试试编译一下 看看能不能通过
直接在IE11中访问http://localhost:8089/就会重现现错误

**Comment by yiwuyu** [comment]
已经修复，但本demo还有很多未完善，接口和数据获取暂时没有实现，sorry.

**Comment by zhangjw-ECHO** [comment]
我感觉写的很好 有个地方设计的不是很合理 就是工具栏中 饿了吗的tooltip和下拉菜单有冲突

**Comment by yiwuyu** [comment]
感谢，看到问题了，我再想想如何改进~
